// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package taskManager

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID        int64
	Name      string
	Status    bool
	CreatedAt pgtype.Timestamp
}
